spring:
  datasource:
    password: 1234
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
  jpa:
    database: mysql
    properties:
      hibernate:
        dialact: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true