spring:
  profiles:
    include: common
  application:
    name: app-user
server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
    register-with-eureka: true
    fetch-registry: true